- name: Configure firewall rules
  ufw:
    rule: allow
    name: "{{allowed_service}}"
  with_items:
    - OpenSSH
    - mosh
  loop_control:
    loop_var: allowed_service

- name: Enable UFW with default policy
  ufw:
    state: enabled
    logging: low