- hosts: raspi
  become: true
  become_method: sudo
  gather_facts: no
  roles:
    - {role: 'initial', tags: 'initial'}
  vars:
    dist_upgrade: yes
    update_apt_cache: yes
    wireguard: no
    monitoring: no