---
- name: Accept releaseinbfo changes
  command: apt-get update -y --allow-releaseinfo-change
  when: allow_releaseinfo_changes

- name: Check if wireguard is installed
  package_facts:
    manager: "auto"

- name: Install wireguard
  block:
    - name: Install raspberry pi kernel headers
      apt:
        name: ["raspberrypi-kernel-headers"]
        state: present

    - name: Trust Debian repository
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 04EE7237B7D453EC

    - name: Add raspbian unstable
      shell: "echo 'deb http://deb.debian.org/debian/ unstable main' | sudo tee --append /etc/apt/sources.list.d/unstable.list"

    - name: Set priority of testing low so not every package will be updated to testing
      shell: "printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' | sudo tee --append /etc/apt/preferences.d/limit-unstable"

    - name: Update repositories cache and install wireguard
      apt:
        name: ["wireguard"]
        state: present
        update_cache: yes

    - name: Reboot immediately if there was a change.
      reboot:

  when: "'wireguard' not in ansible_facts.packages"