- name: create folder for jounrald config
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: configure filesizes of journald
  template:
    src: files/journalsize.conf.j2
    dest: /etc/systemd/journald.conf.d/journalsize.conf
    backup: yes
  register: result

- name: reload configuration of journald to activate journalsize configuration
  service:
    name: systemd-journald.service
    state: restarted
  when: result is changed