---
- name: Upgrade
  apt:
    upgrade: dist
    update_cache: "{{ update_apt_cache }}"
  register: task_result
  when: upgrade

- name: Reboot immediately if there was a change.
  reboot:
  when: task_result is changed

- name: Update repositories cache and install common software
  apt:
    name: "{{ software }}"
    state: present
    update_cache: "{{ update_apt_cache }}"

