---
- name: Upgrade
  apt:
    upgrade: dist
    update_cache: "{{ update_apt_cache }}"
  when: upgrade

- name: Update repositories cache and install common server software
  apt:
    name: "{{ software }}"
    state: present
    update_cache: "{{ update_apt_cache }}"

