---

- name: Accept releaseinbfo changes
  command: apt-get update -y --allow-releaseinfo-change
  when: allow_releaseinfo_changes

- name: Upgrade
  apt:
    upgrade: dist
    update_cache: "{{ update_apt_cache }}"
  async: 3600
  poll: 30
  notify: Reboot host and wait for it to restart
  when: upgrade

# reboot because ufw error "cannot determine iptables version" -> last answer here recommedns reboot https://raspberrypi.stackexchange.com/questions/100598/ufw-and-iptables-on-buster
- name: Update repositories cache and install common software
  apt:
    name: "{{ software }}"
    state: latest
    update_cache: "{{ update_apt_cache }}"
  notify: Reboot host and wait for it to restart

