- name: Configure firewall rules
  ufw:
    rule: allow
    name: "{{ item }}"
  with_items: "{{ allowed_services }}"

- name: Enable UFW with default policy
  ufw:
    state: enabled
    logging: low