---
- group:
    name: admin
    state: present

- name: Allow admin group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: Add user
  user: 
    name: "{{ item.name }}"
    comment: "{{ item.name }} - Administrator"
    shell: /bin/bash
    group: admin
  loop: "{{ ssh_user }}"

- name: Add ssh public key for user
  authorized_key: 
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
    state: present
    exclusive: False
  loop: "{{ ssh_user }}"

- name: Add user ansible
  user: 
    name: "{{ ansible_user_name }}"
    comment: "Ansible User"
    shell: /bin/bash
    group: admin

- name: Add ssh public key for user ansible 
  authorized_key: 
    user: "{{ ansible_user_name }}"
    key: "{{ ansible_ssh_public_key }}"
    state: present
    exclusive: False
    key_options: 'no-port-forwarding'