upgrade: no
update_apt_cache: no
allow_releaseinfo_changes: no
hostname: "testpi"

#ssh user
ansible_user_name: ansible_ssh
ansible_user: "{{ ansible_user_name }}"
ansible_ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa_ansible.pub') }}"
ssh_user:
  - { name: "my_ssh_user", public_key: "{{ lookup('file', '~/.ssh/id_rsa_private.pub') }}" }

#sshd_config.j2 Variables
permit_empty_passwords: "no"
max_auth_tries: "6"
login_grace_time: "1m"
password_authentication: "no"
x11_forwarding: "no"
ssh_port: "22"

software:
  - mosh
  - ufw
  - git
  - vim
  - fail2ban

allowed_services:
  - ssh
  - mosh

#dhcpcd config for static ip
set_static_ip: no
static_interface: "wlan0"
static_ip: "192.168.0.22"
static_router: "192.168.0.1"
dns: "8.8.8.8 192.168.0.1"

#journald config
SystemMaxUse: "64M"
SystemMaxFileSize: "8M"
MaxRetentionSec: "2weeks"
Storage: "persistent"